import path from 'node:path'
import fs from 'node:fs'
import { defineConfig, type Plugin } from 'vite'
// vite-react-ssg adds `ssgOptions` to UserConfig; types don't expose it from vite directly.
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'
import { LANDINGS } from './src/content/landings'

// Serves the MT ffmpeg core files (~31MB wasm + glue + worker) from node_modules
// during dev + preview so MT can be tested locally with zero CDN setup. In prod
// these paths need to resolve on the deployed host — either by copying into
// public/ (paid Pages plan, no 25MB cap) or via a Cloudflare proxy/redirect.
//
// ESM build (not UMD): @ffmpeg/ffmpeg spawns a module worker, which can only
// pull the core in via dynamic `import()`. UMD isn't importable that way and
// fails with "failed to import ffmpeg-core.js".
const MT_CORE_DIR = path.resolve(__dirname, 'node_modules/@ffmpeg/core-mt/dist/esm')
const MT_FILES = new Set(['ffmpeg-core.js', 'ffmpeg-core.wasm', 'ffmpeg-core.worker.js'])

function serveMtCore(req: { url?: string }, res: { setHeader: (k: string, v: string) => void; end: (data?: Buffer) => void; statusCode: number }, next: (err?: unknown) => void) {
  const url = req.url
  if (!url || !url.startsWith('/ffmpeg-mt/')) return next()
  const filename = url.slice('/ffmpeg-mt/'.length).split('?')[0]
  if (!MT_FILES.has(filename)) return next()
  const filePath = path.join(MT_CORE_DIR, filename)
  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.statusCode = 404
      res.end()
      return
    }
    res.setHeader('Content-Type', filename.endsWith('.wasm') ? 'application/wasm' : 'text/javascript')
    res.setHeader('Cache-Control', 'no-cache')
    res.end(data)
  })
}

const mtCoreServe = (): Plugin => ({
  name: 'mt-core-serve',
  configureServer(server) {
    server.middlewares.use(serveMtCore)
  },
  configurePreviewServer(server) {
    server.middlewares.use(serveMtCore)
  },
})

// Mirror the prod _headers rule: cross-origin isolation only on /studio/*.
// SharedArrayBuffer needs this to enable ffmpeg-wasm's multi-threaded core.
// Path-scoped so the landing route stays free of COEP and its third-party
// loading constraints, matching Cloudflare Pages behavior in dev + preview.
//
// COOP only goes on document responses (turns isolation on for the page).
// COEP + CORP go on every response: COEP on subresources is what lets
// workers spawn inside an isolated context (Vite's `?worker_file` script
// gets blocked otherwise), and CORP: same-origin tags same-origin assets
// as safe to embed. Setting them on every response is a no-op for the
// non-isolated landing page and required for the isolated studio page.
function setCoiResponseHeaders(req: { url?: string }, res: { setHeader: (k: string, v: string) => void }) {
  if (req.url && req.url.startsWith('/studio')) {
    res.setHeader('Cross-Origin-Opener-Policy', 'same-origin')
  }
  res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
  res.setHeader('Cross-Origin-Resource-Policy', 'same-origin')
}

const studioCoiHeaders = (): Plugin => ({
  name: 'studio-coi-headers',
  configureServer(server) {
    server.middlewares.use((req, res, next) => {
      setCoiResponseHeaders(req, res)
      next()
    })
  },
  configurePreviewServer(server) {
    server.middlewares.use((req, res, next) => {
      setCoiResponseHeaders(req, res)
      next()
    })
  },
})

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    // Order matters: studioCoiHeaders runs first so COEP/CORP headers are
    // attached to every response — including the MT core files served by
    // mtCoreServe, which calls res.end() and would otherwise short-circuit
    // any later header middleware.
    studioCoiHeaders(),
    mtCoreServe(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.svg'],
      manifest: {
        name: 'WMC | Crop once, post everywhere',
        short_name: 'WMC',
        description:
          'Crop any image to any platform size, right in your browser. Nothing uploaded.',
        theme_color: '#0a0a0a',
        background_color: '#ffffff',
        display: 'standalone',
        start_url: '/',
        scope: '/',
        icons: [
          { src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,ico,woff2}'],
        // No navigateFallback — landing pages at /<slug>/ are real HTML files
        // generated by scripts/gen-landings.ts and must not be rewritten to /.
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
    dedupe: ['react', 'react-dom'],
  },
  // @ts-expect-error — `ssgOptions` is augmented onto UserConfig by vite-react-ssg
  ssgOptions: {
    script: 'async',
    formatting: 'minify',
    includedRoutes() {
      return ['/', ...LANDINGS.map((l) => `/${l.slug}`)]
    },
  },
})